import type { Job, DailyMetrics } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: 1,
    title: "Desenvolvedor FullStack Java + React",
    companyName: "Nubank",
    link: "https://nubank.com.br/carreiras",
    source: "LinkedIn",
    remote: true,
    hybrid: false,
    level: "Pleno",
    techs: ["Java", "Spring Boot", "React", "TypeScript", "Kafka"],
    salaryMin: 8000,
    salaryMax: 14000,
    salaryInformed: true,
    location: "São Paulo, SP",
    finalScore: 94,
    scoreMl: 0.91,
    scoreBreakdown: { techs: 0.95, level: 0.90, salary: 0.88 },
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Backend Engineer — Python & FastAPI",
    companyName: "iFood",
    link: "https://careers.ifood.com.br",
    source: "Gupy",
    remote: true,
    hybrid: false,
    level: "Pleno",
    techs: ["Python", "FastAPI", "PostgreSQL", "Docker", "Redis"],
    salaryMin: 9000,
    salaryMax: 15000,
    salaryInformed: true,
    location: "Remoto",
    finalScore: 88,
    scoreMl: 0.85,
    scoreBreakdown: { techs: 0.90, level: 0.88, salary: 0.82 },
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Engenheiro de Software FullStack",
    companyName: "Totvs",
    link: "https://totvs.gupy.io",
    source: "Gupy",
    remote: false,
    hybrid: true,
    level: "Pleno",
    techs: ["TypeScript", "NestJS", "Next.js", "PostgreSQL"],
    salaryMin: 7000,
    salaryMax: 11000,
    salaryInformed: true,
    location: "São Paulo, SP",
    finalScore: 82,
    scoreMl: 0.79,
    scoreBreakdown: { techs: 0.85, level: 0.80, salary: 0.75 },
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Desenvolvedor Java Sênior",
    companyName: "Bradesco",
    link: "https://bradesco.gupy.io",
    source: "LinkedIn",
    remote: false,
    hybrid: true,
    level: "Sênior",
    techs: ["Java 17", "Spring Boot", "Microservices", "AWS", "Oracle"],
    salaryMin: 12000,
    salaryMax: 18000,
    salaryInformed: true,
    location: "Osasco, SP",
    finalScore: 76,
    scoreMl: 0.72,
    scoreBreakdown: { techs: 0.80, level: 0.70, salary: 0.72 },
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    title: "Desenvolvedor Node.js + TypeScript",
    companyName: "Mercado Livre",
    link: "https://mercadolivre.gupy.io",
    source: "Gupy",
    remote: true,
    hybrid: false,
    level: "Pleno",
    techs: ["Node.js", "TypeScript", "React", "MongoDB", "Docker"],
    salaryMin: 8500,
    salaryMax: 13000,
    salaryInformed: true,
    location: "Remoto",
    finalScore: 85,
    scoreMl: 0.82,
    scoreBreakdown: { techs: 0.88, level: 0.84, salary: 0.80 },
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    title: "Software Engineer — Machine Learning Platform",
    companyName: "Stone",
    link: "https://stone.gupy.io",
    source: "LinkedIn",
    remote: true,
    hybrid: false,
    level: "Pleno",
    techs: ["Python", "PyTorch", "FastAPI", "Kubernetes", "MLflow"],
    salaryMin: 10000,
    salaryMax: 16000,
    salaryInformed: true,
    location: "Remoto",
    finalScore: 79,
    scoreMl: 0.76,
    scoreBreakdown: { techs: 0.82, level: 0.75, salary: 0.78 },
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_METRICS: DailyMetrics = {
  date: new Date().toISOString().split("T")[0],
  jobsCollected: 47,
  jobsScored: 47,
  jobsNotified: 6,
  applicationsSent: 3,
  responsesReceived: 1,
  interviewsScheduled: 0,
  callbackRate: 33.3,
};
